; Listing generated by Microsoft (R) Optimizing Compiler Version 19.35.32217.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__C08AB69B_s_instruction_handler@h DB 01H
__C3D862C9_s_instruction_handler@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?ExtractOperation@@YAHAEAH@Z			; ExtractOperation
PUBLIC	?ExtractOperand@@YAHAEAH@Z			; ExtractOperand
PUBLIC	?GetDigits@@YAHH@Z				; GetDigits
PUBLIC	__JustMyCode_Default
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?ExtractOperation@@YAHAEAH@Z DD imagerel $LN4
	DD	imagerel $LN4+44
	DD	imagerel $unwind$?ExtractOperation@@YAHAEAH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?ExtractOperand@@YAHAEAH@Z DD imagerel $LN4
	DD	imagerel $LN4+57
	DD	imagerel $unwind$?ExtractOperand@@YAHAEAH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?GetDigits@@YAHH@Z DD imagerel $LN11
	DD	imagerel $LN11+58
	DD	imagerel $unwind$?GetDigits@@YAHH@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?GetDigits@@YAHH@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?ExtractOperand@@YAHAEAH@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?ExtractOperation@@YAHAEAH@Z DD 020601H
	DD	030023206H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?GetDigits@@YAHH@Z
_TEXT	SEGMENT
instruction$ = 48
?GetDigits@@YAHH@Z PROC					; GetDigits, COMDAT
; File C:\Users\User\source\repos\Simpletron\s_instruction_handler.cpp
; Line 10
$LN11:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	ebx, ecx
	lea	rcx, OFFSET FLAT:__C3D862C9_s_instruction_handler@cpp
	call	__CheckForDebuggerJustMyCode
	xor	ecx, ecx
	test	ebx, ebx
	jle	SHORT $LN9@GetDigits
	npad	6
$LL2@GetDigits:
; Line 13
	mov	eax, -858993459				; cccccccdH
; Line 14
	inc	ecx
	mul	ebx
	mov	ebx, edx
	shr	ebx, 3
	test	ebx, ebx
	jg	SHORT $LL2@GetDigits
$LN9@GetDigits:
; Line 17
	mov	eax, ecx
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
?GetDigits@@YAHH@Z ENDP					; GetDigits
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?ExtractOperand@@YAHAEAH@Z
_TEXT	SEGMENT
instruction$ = 48
?ExtractOperand@@YAHAEAH@Z PROC				; ExtractOperand, COMDAT
; File C:\Users\User\source\repos\Simpletron\s_instruction_handler.cpp
; Line 6
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	lea	rcx, OFFSET FLAT:__C3D862C9_s_instruction_handler@cpp
	call	__CheckForDebuggerJustMyCode
	mov	r8d, DWORD PTR [rbx]
	mov	eax, 1374389535				; 51eb851fH
	imul	r8d
	sar	edx, 5
	mov	ecx, edx
	shr	ecx, 31
	add	edx, ecx
	imul	ecx, edx, 100				; 00000064H
	sub	r8d, ecx
	mov	eax, r8d
; Line 8
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
?ExtractOperand@@YAHAEAH@Z ENDP				; ExtractOperand
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?ExtractOperation@@YAHAEAH@Z
_TEXT	SEGMENT
instruction$ = 48
?ExtractOperation@@YAHAEAH@Z PROC			; ExtractOperation, COMDAT
; File C:\Users\User\source\repos\Simpletron\s_instruction_handler.cpp
; Line 2
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	lea	rcx, OFFSET FLAT:__C3D862C9_s_instruction_handler@cpp
	call	__CheckForDebuggerJustMyCode
	mov	eax, 1374389535				; 51eb851fH
	imul	DWORD PTR [rbx]
	sar	edx, 5
	mov	eax, edx
	shr	eax, 31
	add	eax, edx
; Line 4
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
?ExtractOperation@@YAHAEAH@Z ENDP			; ExtractOperation
_TEXT	ENDS
END
